name: PR Label-based Discord Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}

    steps:
      - name: Notify Discord based on PR label
        run: |
          LABELS=$(echo "$PR_LABELS_JSON" | jq -r '.[].name')
          
          for LABEL in $LABELS; do
            case "$LABEL" in
              "backend")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_BACKEND }}"
                ;;
              "frontend")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_FRONTEND }}"
                ;;
              *)
                continue
                ;;
            esac
          
            MESSAGE="$PR_URL"
            if [ -z "$WEBHOOK_URL" ]; then
              echo "Webhook URL not set for label $LABEL. Skipping."
              continue
            fi
          
            if [ -z "$MESSAGE" ]; then
              echo "Message is empty. Skipping."
              continue
            fi
          
            PAYLOAD=$(jq -n --arg content "$MESSAGE" '{content: $content}')
          
            curl --fail -H "Content-Type: application/json" \
              -X POST \
              -d "$PAYLOAD" \
              "$WEBHOOK_URL"
          done
